services:
  - type: web
    name: influxdb
    env: docker
    region: oregon
    plan: standard
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8086
    disk:
      name: influxdb-data
      mountPath: /var/lib/influxdb2
      sizeGB: 10
